//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierAdmission
    {
        public decimal ID_Admission { get; set; }
        public System.DateTime Date_admission { get; set; }
        public System.DateTime Date_chirurgie { get; set; }
        public Nullable<System.DateTime> Date_conge { get; set; }
        public decimal NSS { get; set; }
        public string Numero_lit { get; set; }
        public Nullable<decimal> ID_TypeChirurgie { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual TypeChirurgie TypeChirurgie { get; set; }
        public virtual Lit Lit { get; set; }
    }
}
