//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public decimal ID { get; set; }
        public decimal NSS { get; set; }
        public decimal ID_Frais { get; set; }
        public decimal Qte { get; set; }
    
        public virtual Frais Frais { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
