//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Frais()
        {
            this.Facture = new HashSet<Facture>();
        }
    
        public decimal ID_frais { get; set; }
        public string Nom { get; set; }
        public Nullable<decimal> ID_TypeChambre { get; set; }
        public decimal Prix { get; set; }
        public Nullable<decimal> ID_Commodite { get; set; }
    
        public virtual TypeChambre TypeChambre { get; set; }
        public virtual TypeCommodite TypeCommodite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
    }
}
