//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospytalEntities2 : DbContext
    {
        public HospytalEntities2()
            : base("name=HospytalEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compagnie_Assurance> Compagnie_Assurance { get; set; }
        public virtual DbSet<Departemente> Departemente { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeChambre> TypeChambre { get; set; }
        public virtual DbSet<TypeCommodite> TypeCommodite { get; set; }
        public virtual DbSet<TypeChirurgie> TypeChirurgie { get; set; }
        public virtual DbSet<DossierAdmission> DossierAdmission { get; set; }
        public virtual DbSet<Frais> Frais { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<Medecin> Medecin { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Chambre> Chambre { get; set; }
        public virtual DbSet<TypeLit> TypeLit { get; set; }
        public virtual DbSet<Lit> Lit { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
    }
}
