//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.DossierAdmission = new HashSet<DossierAdmission>();
            this.Facture = new HashSet<Facture>();
        }
    
        public decimal NSS { get; set; }
        public Nullable<System.DateTime> Date_Naissance { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string Code_postal { get; set; }
        public decimal Telephone { get; set; }
        public decimal ID_Medicin { get; set; }
        public Nullable<decimal> ID_Compagnie { get; set; }
        public Nullable<decimal> Ref_parent { get; set; }
    
        public virtual Compagnie_Assurance Compagnie_Assurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DossierAdmission> DossierAdmission { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual Medecin Medecin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
    }
}
